"""Pure country-fact normalization and deterministic compliance routing."""

from __future__ import annotations

from signals.compliance.contracts import (
    JURISDICTION_VERSION,
    ComplianceJurisdiction,
    JurisdictionResolution,
)

EU_MEMBER_CODES = frozenset(
    {
        "AT",
        "BE",
        "BG",
        "HR",
        "CY",
        "CZ",
        "DK",
        "EE",
        "FI",
        "FR",
        "DE",
        "GR",
        "HU",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MT",
        "NL",
        "PL",
        "PT",
        "RO",
        "SK",
        "SI",
        "ES",
        "SE",
    }
)

# Explicit ISO 3166-1 alpha-2 recognition prevents arbitrary two-character
# provider values from being treated as authoritative country evidence.
ISO_ALPHA2_CODES = frozenset(
    [
        "AD",
        "AE",
        "AF",
        "AG",
        "AI",
        "AL",
        "AM",
        "AO",
        "AQ",
        "AR",
        "AS",
        "AT",
        "AU",
        "AW",
        "AX",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BL",
        "BM",
        "BN",
        "BO",
        "BQ",
        "BR",
        "BS",
        "BT",
        "BV",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CC",
        "CD",
        "CF",
        "CG",
        "CH",
        "CI",
        "CK",
        "CL",
        "CM",
        "CN",
        "CO",
        "CR",
        "CU",
        "CV",
        "CW",
        "CX",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "EH",
        "ER",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FK",
        "FM",
        "FO",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GF",
        "GG",
        "GH",
        "GI",
        "GL",
        "GM",
        "GN",
        "GP",
        "GQ",
        "GR",
        "GS",
        "GT",
        "GU",
        "GW",
        "GY",
        "HK",
        "HM",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IM",
        "IN",
        "IO",
        "IQ",
        "IR",
        "IS",
        "IT",
        "JE",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KP",
        "KR",
        "KW",
        "KY",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MF",
        "MG",
        "MH",
        "MK",
        "ML",
        "MM",
        "MN",
        "MO",
        "MP",
        "MQ",
        "MR",
        "MS",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NC",
        "NE",
        "NF",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NU",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PF",
        "PG",
        "PH",
        "PK",
        "PL",
        "PM",
        "PN",
        "PR",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RE",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SD",
        "SE",
        "SG",
        "SH",
        "SI",
        "SJ",
        "SK",
        "SL",
        "SM",
        "SN",
        "SO",
        "SR",
        "SS",
        "ST",
        "SV",
        "SX",
        "SY",
        "SZ",
        "TC",
        "TD",
        "TF",
        "TG",
        "TH",
        "TJ",
        "TK",
        "TL",
        "TM",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "UM",
        "US",
        "UY",
        "UZ",
        "VA",
        "VC",
        "VE",
        "VG",
        "VI",
        "VN",
        "VU",
        "WF",
        "WS",
        "YE",
        "YT",
        "ZA",
        "ZM",
        "ZW",
    ]
)

_PROVIDER_COUNTRY_ALIASES = {
    "austria": "AT",
    "belgium": "BE",
    "bulgaria": "BG",
    "croatia": "HR",
    "cyprus": "CY",
    "czech republic": "CZ",
    "czechia": "CZ",
    "denmark": "DK",
    "estonia": "EE",
    "finland": "FI",
    "france": "FR",
    "germany": "DE",
    "greece": "GR",
    "hungary": "HU",
    "ireland": "IE",
    "italy": "IT",
    "latvia": "LV",
    "lithuania": "LT",
    "luxembourg": "LU",
    "malta": "MT",
    "netherlands": "NL",
    "poland": "PL",
    "portugal": "PT",
    "romania": "RO",
    "slovakia": "SK",
    "slovenia": "SI",
    "spain": "ES",
    "sweden": "SE",
    "switzerland": "CH",
    "united states": "US",
    "united states of america": "US",
    "united kingdom": "GB",
    "uk": "GB",
}


def normalize_provider_country(value: str | None) -> str | None:
    if value is None:
        return None
    normalized = " ".join(value.casefold().split())
    alias = _PROVIDER_COUNTRY_ALIASES.get(normalized)
    if alias is not None:
        return alias
    candidate = normalized.upper()
    return candidate if candidate in ISO_ALPHA2_CODES else None


def _normalize_supplier_country(value: str | None) -> str | None:
    if value is None:
        return None
    candidate = value.strip().upper()
    return candidate if candidate in ISO_ALPHA2_CODES else None


def resolve_jurisdiction(
    *,
    supplier_country_code: str | None,
    provider_country: str | None,
    supplier_ref: str,
    profile_ref: str,
) -> JurisdictionResolution:
    supplier = _normalize_supplier_country(supplier_country_code)
    provider = normalize_provider_country(provider_country)
    refs = []
    if supplier:
        refs.append(f"acquisition-supplier:{supplier_ref}:country")
    if provider:
        refs.append(f"{profile_ref}:provider-country")
    if supplier and provider and supplier != provider:
        return JurisdictionResolution(
            jurisdiction=ComplianceJurisdiction.UNRESOLVED,
            resolvable=True,
            evidence_refs=tuple(refs),
        )
    country = supplier or provider
    if country is None:
        return JurisdictionResolution(
            jurisdiction=ComplianceJurisdiction.UNRESOLVED,
            resolvable=True,
            evidence_refs=(f"{profile_ref}:country-unresolved",),
        )
    if country == "CH":
        jurisdiction = ComplianceJurisdiction.CH
    elif country == "FR":
        jurisdiction = ComplianceJurisdiction.FR
    elif country in EU_MEMBER_CODES:
        jurisdiction = ComplianceJurisdiction.EU_MEMBER_STATE_UNCONFIGURED
    else:
        jurisdiction = ComplianceJurisdiction.OUT_OF_SCOPE
    return JurisdictionResolution(
        jurisdiction=jurisdiction,
        country_code=country,
        resolvable=jurisdiction is not ComplianceJurisdiction.OUT_OF_SCOPE,
        evidence_refs=tuple(refs),
    )


__all__ = [
    "EU_MEMBER_CODES",
    "ISO_ALPHA2_CODES",
    "JURISDICTION_VERSION",
    "normalize_provider_country",
    "resolve_jurisdiction",
]
