"""initial saas persistence schema

Revision ID: 0001_initial
Revises:
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_event",
        sa.Column("event_key", sa.String(length=256), nullable=False),
        sa.Column("source_system", sa.String(length=32), nullable=False),
        sa.Column("source_notice_id", sa.String(length=256), nullable=False),
        sa.Column("notice_version", sa.String(length=32), nullable=True),
        sa.Column("source_country", sa.String(length=2), nullable=False),
        sa.Column("source_procedure_id", sa.String(length=256), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("published_at_raw", sa.String(length=64), nullable=True),
        sa.Column("published_on", sa.Date(), nullable=True),
        sa.Column("published_precision", sa.String(length=16), nullable=True),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("procedure_buyers", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("event_key"),
    )
    op.create_index(
        op.f("ix_source_event_published_on"), "source_event", ["published_on"], unique=False
    )
    op.create_table(
        "contract_award",
        sa.Column("award_key", sa.String(length=64), nullable=False),
        sa.Column("event_key", sa.String(length=256), nullable=False),
        sa.Column("source_award_id", sa.String(length=256), nullable=True),
        sa.Column("lot_identifier", sa.String(length=256), nullable=True),
        sa.Column("lot_title", sa.Text(), nullable=True),
        sa.Column("contract_reference", sa.String(length=256), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("cpv_main", sa.String(length=8), nullable=True),
        sa.Column("cpv_check_digit", sa.String(length=1), nullable=True),
        sa.Column("cpv_additional", sa.JSON(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("vat_category", sa.String(length=32), nullable=True),
        sa.Column("winner_status", sa.String(length=16), nullable=False),
        sa.Column("awardee_parties", sa.JSON(), nullable=False),
        sa.Column("contract_signatories", sa.JSON(), nullable=False),
        sa.Column("place_of_performance", sa.JSON(), nullable=True),
        sa.Column("place_country", sa.String(length=2), nullable=True),
        sa.Column("award_date", sa.Date(), nullable=True),
        sa.Column("contract_signature_date", sa.Date(), nullable=True),
        sa.Column("contract_notification_date", sa.Date(), nullable=True),
        sa.Column("contract_start_date", sa.Date(), nullable=True),
        sa.Column("contract_end_date", sa.Date(), nullable=True),
        sa.Column("duration_value", sa.Integer(), nullable=True),
        sa.Column("duration_unit", sa.String(length=16), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_key"], ["source_event.event_key"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("award_key"),
    )
    op.create_index(
        op.f("ix_contract_award_award_date"), "contract_award", ["award_date"], unique=False
    )
    op.create_index(
        op.f("ix_contract_award_contract_notification_date"),
        "contract_award",
        ["contract_notification_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contract_award_cpv_main"), "contract_award", ["cpv_main"], unique=False
    )
    op.create_index(
        op.f("ix_contract_award_event_key"), "contract_award", ["event_key"], unique=False
    )
    op.create_index(
        op.f("ix_contract_award_place_country"), "contract_award", ["place_country"], unique=False
    )
    op.create_table(
        "evidence",
        sa.Column("evidence_key", sa.String(length=64), nullable=False),
        sa.Column("award_key", sa.String(length=64), nullable=False),
        sa.Column("anchors_kind", sa.String(length=32), nullable=False),
        sa.Column("anchors_ref", sa.String(length=128), nullable=False),
        sa.Column("source_system", sa.String(length=32), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("source_notice_id", sa.String(length=256), nullable=True),
        sa.Column("source_procedure_id", sa.String(length=256), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("path", sa.Text(), nullable=True),
        sa.Column("raw_value", sa.Text(), nullable=True),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("engine_version", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["award_key"], ["contract_award.award_key"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("evidence_key"),
    )
    op.create_index(op.f("ix_evidence_award_key"), "evidence", ["award_key"], unique=False)
    op.create_table(
        "materialized_signal",
        sa.Column("signal_key", sa.String(length=64), nullable=False),
        sa.Column("opportunity_key", sa.String(length=64), nullable=False),
        sa.Column("materialization_award_key", sa.String(length=64), nullable=False),
        sa.Column("target_icp_id", sa.String(length=128), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("content_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("materialized_recency_status", sa.String(length=32), nullable=False),
        sa.Column("materialized_primary_event", sa.String(length=32), nullable=True),
        sa.Column("materialized_award_clock_status", sa.String(length=16), nullable=False),
        sa.Column("materialized_notification_clock_status", sa.String(length=16), nullable=False),
        sa.Column("materialized_publication_clock_status", sa.String(length=16), nullable=False),
        sa.Column("materialized_award_age_days", sa.Integer(), nullable=True),
        sa.Column("materialized_notification_age_days", sa.Integer(), nullable=True),
        sa.Column("materialized_publication_age_days", sa.Integer(), nullable=True),
        sa.Column("materialized_as_of", sa.Date(), nullable=False),
        sa.Column("recency_policy_version", sa.String(length=64), nullable=False),
        sa.Column("winner_name", sa.Text(), nullable=True),
        sa.Column("winner_country", sa.String(length=2), nullable=True),
        sa.Column("winner_identifier_scheme", sa.String(length=64), nullable=True),
        sa.Column("winner_identifier_value", sa.String(length=128), nullable=True),
        sa.Column("inferred_contract_type", sa.String(length=64), nullable=True),
        sa.Column("inferred_sector", sa.String(length=64), nullable=True),
        sa.Column("inferred_trade_domain", sa.String(length=64), nullable=True),
        sa.Column("inferred_contract_summary", sa.Text(), nullable=True),
        sa.Column("plausible_needs", sa.JSON(), nullable=False),
        sa.Column("icp_match_decision", sa.String(length=32), nullable=True),
        sa.Column("icp_match_band", sa.String(length=32), nullable=True),
        sa.Column("icp_match_confidence", sa.String(length=32), nullable=True),
        sa.Column("icp_match_normalized_score", sa.Integer(), nullable=True),
        sa.Column("icp_matched_needs", sa.JSON(), nullable=False),
        sa.Column("engine_versions", sa.JSON(), nullable=False),
        sa.Column("materialized_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["materialization_award_key"], ["contract_award.award_key"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("signal_key"),
        sa.UniqueConstraint(
            "opportunity_key", "target_icp_id", name="uq_signal_opportunity_target_icp"
        ),
    )
    op.create_index(
        op.f("ix_materialized_signal_materialization_award_key"),
        "materialized_signal",
        ["materialization_award_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_materialized_signal_materialized_primary_event"),
        "materialized_signal",
        ["materialized_primary_event"],
        unique=False,
    )
    op.create_index(
        op.f("ix_materialized_signal_materialized_recency_status"),
        "materialized_signal",
        ["materialized_recency_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_materialized_signal_opportunity_key"),
        "materialized_signal",
        ["opportunity_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_materialized_signal_target_icp_id"),
        "materialized_signal",
        ["target_icp_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_materialized_signal_winner_identifier_value"),
        "materialized_signal",
        ["winner_identifier_value"],
        unique=False,
    )
    op.create_table(
        "opportunity_representation",
        sa.Column("award_key", sa.String(length=64), nullable=False),
        sa.Column("opportunity_key", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["award_key"], ["contract_award.award_key"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("award_key"),
    )
    op.create_index(
        op.f("ix_opportunity_representation_opportunity_key"),
        "opportunity_representation",
        ["opportunity_key"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_opportunity_representation_opportunity_key"),
        table_name="opportunity_representation",
    )
    op.drop_table("opportunity_representation")
    op.drop_index(
        op.f("ix_materialized_signal_winner_identifier_value"), table_name="materialized_signal"
    )
    op.drop_index(op.f("ix_materialized_signal_target_icp_id"), table_name="materialized_signal")
    op.drop_index(op.f("ix_materialized_signal_opportunity_key"), table_name="materialized_signal")
    op.drop_index(
        op.f("ix_materialized_signal_materialized_recency_status"), table_name="materialized_signal"
    )
    op.drop_index(
        op.f("ix_materialized_signal_materialized_primary_event"), table_name="materialized_signal"
    )
    op.drop_index(
        op.f("ix_materialized_signal_materialization_award_key"), table_name="materialized_signal"
    )
    op.drop_table("materialized_signal")
    op.drop_index(op.f("ix_evidence_award_key"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_contract_award_place_country"), table_name="contract_award")
    op.drop_index(op.f("ix_contract_award_event_key"), table_name="contract_award")
    op.drop_index(op.f("ix_contract_award_cpv_main"), table_name="contract_award")
    op.drop_index(op.f("ix_contract_award_contract_notification_date"), table_name="contract_award")
    op.drop_index(op.f("ix_contract_award_award_date"), table_name="contract_award")
    op.drop_table("contract_award")
    op.drop_index(op.f("ix_source_event_published_on"), table_name="source_event")
    op.drop_table("source_event")
    # ### end Alembic commands ###
