"""billing

Revision ID: 0003_billing
Revises: 0002_account_auth_target_icp
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0003_billing"
down_revision = "0002_account_auth_target_icp"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stripe_webhook_event",
        sa.Column("stripe_event_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("stripe_object_id", sa.String(length=128), nullable=True),
        sa.Column("livemode", sa.Boolean(), nullable=False),
        sa.Column("stripe_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processing_result", sa.String(length=32), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("stripe_event_id"),
    )
    op.create_index(
        op.f("ix_stripe_webhook_event_event_type"),
        "stripe_webhook_event",
        ["event_type"],
        unique=False,
    )
    op.create_table(
        "billing_checkout_attempt",
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("attempt_id", sa.String(length=64), nullable=False),
        sa.Column("plan_code", sa.String(length=32), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("stripe_checkout_session_id", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["account.account_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("account_id"),
        sa.UniqueConstraint("attempt_id"),
        sa.UniqueConstraint("stripe_checkout_session_id"),
    )
    op.create_index(
        op.f("ix_billing_checkout_attempt_status"),
        "billing_checkout_attempt",
        ["status"],
        unique=False,
    )
    op.create_table(
        "billing_customer",
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("stripe_customer_id", sa.String(length=128), nullable=False),
        sa.Column("livemode", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["account.account_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("account_id"),
        sa.UniqueConstraint("stripe_customer_id"),
    )
    op.create_table(
        "billing_subscription",
        sa.Column("billing_subscription_id", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("stripe_subscription_id", sa.String(length=128), nullable=False),
        sa.Column("stripe_customer_id", sa.String(length=128), nullable=False),
        sa.Column("stripe_price_id", sa.String(length=128), nullable=True),
        sa.Column("stripe_product_id", sa.String(length=128), nullable=True),
        sa.Column("plan_code", sa.String(length=32), nullable=True),
        sa.Column("offer_code", sa.String(length=32), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_stripe_event_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("livemode", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["account.account_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("billing_subscription_id"),
        sa.UniqueConstraint("account_id"),
        sa.UniqueConstraint("stripe_subscription_id"),
    )
    op.create_index(
        op.f("ix_billing_subscription_plan_code"),
        "billing_subscription",
        ["plan_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_billing_subscription_status"), "billing_subscription", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_billing_subscription_stripe_customer_id"),
        "billing_subscription",
        ["stripe_customer_id"],
        unique=False,
    )
    op.create_table(
        "discovery_signal_grant",
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("signal_key", sa.String(length=64), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("opportunity_key", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["account.account_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("account_id", "signal_key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("discovery_signal_grant")
    op.drop_index(
        op.f("ix_billing_subscription_stripe_customer_id"), table_name="billing_subscription"
    )
    op.drop_index(op.f("ix_billing_subscription_status"), table_name="billing_subscription")
    op.drop_index(op.f("ix_billing_subscription_plan_code"), table_name="billing_subscription")
    op.drop_table("billing_subscription")
    op.drop_table("billing_customer")
    op.drop_index(op.f("ix_billing_checkout_attempt_status"), table_name="billing_checkout_attempt")
    op.drop_table("billing_checkout_attempt")
    op.drop_index(op.f("ix_stripe_webhook_event_event_type"), table_name="stripe_webhook_event")
    op.drop_table("stripe_webhook_event")
    # ### end Alembic commands ###
