"""alerts feedback analytics

Revision ID: 0004_alerts_feedback_analytics
Revises: 0003_billing
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0004_alerts_feedback_analytics"
down_revision = "0003_billing"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_notification_preference",
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("email_enabled", sa.Boolean(), nullable=False),
        sa.Column("notification_email", sa.String(length=320), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["account.account_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("account_id"),
    )
    op.create_table(
        "product_event",
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=True),
        sa.Column("target_icp_id", sa.String(length=128), nullable=True),
        sa.Column("signal_key", sa.String(length=64), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("properties", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["account.account_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_product_event_account_id"), "product_event", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_product_event_event_type"), "product_event", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_product_event_occurred_at"), "product_event", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_product_event_signal_key"), "product_event", ["signal_key"], unique=False
    )
    op.create_table(
        "signal_alert_delivery",
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("signal_key", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("cadence", sa.String(length=16), nullable=False),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("provider_message_id", sa.String(length=255), nullable=True),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["account.account_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("account_id", "signal_key"),
    )
    op.create_index(
        op.f("ix_signal_alert_delivery_sent_at"), "signal_alert_delivery", ["sent_at"], unique=False
    )
    op.create_index(
        op.f("ix_signal_alert_delivery_status"), "signal_alert_delivery", ["status"], unique=False
    )
    op.create_table(
        "signal_feedback",
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("signal_key", sa.String(length=64), nullable=False),
        sa.Column("relevance", sa.String(length=16), nullable=False),
        sa.Column("reason_code", sa.String(length=32), nullable=True),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("contacted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("event_status_at_feedback", sa.String(length=32), nullable=True),
        sa.Column("event_age_days_at_feedback", sa.Integer(), nullable=True),
        sa.Column("signal_revision_at_feedback", sa.Integer(), nullable=True),
        sa.Column("opportunity_key", sa.String(length=64), nullable=True),
        sa.Column("target_icp_id", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["account.account_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("account_id", "signal_key"),
    )
    op.create_index(
        op.f("ix_signal_feedback_reason_code"), "signal_feedback", ["reason_code"], unique=False
    )
    op.create_index(
        op.f("ix_signal_feedback_relevance"), "signal_feedback", ["relevance"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_signal_feedback_relevance"), table_name="signal_feedback")
    op.drop_index(op.f("ix_signal_feedback_reason_code"), table_name="signal_feedback")
    op.drop_table("signal_feedback")
    op.drop_index(op.f("ix_signal_alert_delivery_status"), table_name="signal_alert_delivery")
    op.drop_index(op.f("ix_signal_alert_delivery_sent_at"), table_name="signal_alert_delivery")
    op.drop_table("signal_alert_delivery")
    op.drop_index(op.f("ix_product_event_signal_key"), table_name="product_event")
    op.drop_index(op.f("ix_product_event_occurred_at"), table_name="product_event")
    op.drop_index(op.f("ix_product_event_event_type"), table_name="product_event")
    op.drop_index(op.f("ix_product_event_account_id"), table_name="product_event")
    op.drop_table("product_event")
    op.drop_table("account_notification_preference")
    # ### end Alembic commands ###
